<?php
	/*
		1) OBTENER LISTADO DE USUARIOS (AYUDANTES)
		2) OBTENER LISTADO DE TODAS LAS CARRERAS (ASOCIADAS A INSTITUCION)
		3) PODER SELECCIONAR A LOS USUARIOS Y UNIRLOS A UNA CARRERA

		ESTO PERMITE ASOCIAR UN AYUDANTE A UNA CARRERA DE ALGUNA INSTITUCION

	*/
?>