<?php
	/*
		1) OBTENER ID DE INSTITUCION
		2) OBTENER LISTADO DE TODAS LAS CARRERAS
		3) AÑADIRLES UN CHECKBOX PARA DAR LA POSIBILIDAD DE ASOCIAR TODAS LAS CARRERAS POSIBLES REGISTRADAS A LA INSTITUCION

	*/
?>